const products = [
  {
    id: 0,
    name: "Tomatoes",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product1.jpeg",
  },
  {
    id: 1,
    name: "Limes",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product8.jpeg",
  },
  {
    id: 2,
    name: "Eggplants",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product2.jpeg",
  },
  {
    id: 3,
    name: "Zucchini",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product3.jpeg",
  },
  {
    id: 4,
    name: "Snap Pea",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product4.jpeg",
  },
  {
    id: 5,
    name: "Butter Lettuce",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product5.jpeg",
  },
  {
    id: 6,
    name: "Olives",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product6.jpeg",
  },
  {
    id: 7,
    name: "Cabage",
    price: 370,
    instock: 100,
    description: "lorem ipsum",
    imgSrc: "./assets/product7.jpeg",
  },
];
